### ISSUE TITLE
Project 2 - Due Monday at midnight

### ISSUE THREAD

**Issue by kalminos** [AceHao/CS-3B-PCC-Map#1]
Object-Oriented Design

1.) Create a top-down design by breaking your requirement document into nouns and verb
2.) Create a list of data which you think your program needs - (bottom-up)
3.) Put the related groups together - Start with the first datum (element) and then find related data (elements)
4.) Add methods from verb list
5.) Add any elements you think will be needed in the future
6.) Cross-reference the two lists you have to find any missing data or functions
7.) Create a table for the domain and range of your data. Be sure to consider cases of error, or out-of-range and how they will be addressed.

(Note: I edited these for grammar and clarity since it was bugging me. -Joe)

**Comment by joerenzullo** [comment]
If nobody has had time by tomorrow, I'll start by tackling the first item, and we can collaborate from there on the rest.

**Comment by kalminos** [comment]
remind me, top down was looking at the desired final result and thinking of what classes are needed, what was bottom-up?
